[package]
name = "proto"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[build-dependencies]
protoc-rust = "2.0"

[dependencies]
protobuf = { version = "~2.0", features = ["with-bytes"] }
